### ISSUE TITLE
发现貌似不支持python3

### ISSUE THREAD

**Issue by loocao** [yueyoum/social-oauth#15]
如**init**.py 54行:
`for _k, _v in _site_config.iteritems():`
这个项目现在还有维护吗？

**Comment by ghost** [comment]
@oncereply 已经三年不更新，显然没有维护了。最近正好要用到这个功能，就参照作者的写作思路自己重新fork一个分支吧。

**Comment by yueyoum** [comment]
@oncereply @zmrenwu 
不好意思， 挖坑却没填好

去年到现在一直忙， 
我更希望 大家 发点 pull request， 这样我也会有时间来 跟新维护。

甚至 可以建立一个 organization  ， 万一我太忙， 还有大家可以来维护这个库

**Comment by ghost** [comment]
@ 嗯，很惊奇的发现 3 年了新浪的 API 依然可以用，只要加一些 py3 的支持就可以了，过几天我整理一下发个pr

**Comment by loocao** [comment]
@zmrenwu 顶一个,我自个clone开了个分支 [python3](https://github.com/oncereply/social-oauth/tree/python3) ,因为只改了自己用到的部分代码,所以没有提交pr

**Comment by yueyoum** [comment]
@zmrenwu  @oncereply 
我已经建立一个 social-oauth 的组织， 已经邀请大家了，
大家 先加进去， 到时候 直接在 组织里 提交代码
